package main

import "testing"

func TestPart1(t *testing.T) {
	t.Run("should return 21", func(t *testing.T) {
		actual := Part1(`.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`)
		expected := int(21)

		if actual != expected {
			t.Errorf("got %d want %d", actual, expected)
		}
	})
}

func TestPart2(t *testing.T) {
	t.Run("should return 40", func(t *testing.T) {
		actual := Part2(`.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`)
		expected := int(40)

		if actual != expected {
			t.Errorf("got %d want %d", actual, expected)
		}
	})
}
